### PR TITLE
feat: add support for Python 3.11

### LINKED ISSUE #467: add support for Python 3.11
` python-api-core` currently does not indicate support for Python 3.11. It's missing the necessary tests and documentation.

### PR DESCRIPTION
**Pull request by ziegenberg**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-api-core/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #467 🦕

### CODE REVIEW

**Comment by dandhlee** [comment]
Hi there, it doesn't seem like you're working with Google. Could you open a GitHub issue first?

**Comment by ziegenberg** [comment]
> Hi there, it doesn't seem like you're working with Google. Could you open a GitHub issue first?

That's right; I do work with Google. I will open an issue.

_I followed #284 when creating this PR, which also did not have an accompanying issue._

**Comment by ziegenberg** [comment]
The `python -m py.test` call had to be changed to `python -m pytest`, otherwise it would always fail with:

```
Error while finding module specification for 'py.test' (ModuleNotFoundError: __path__ attribute not found on 'py' while trying to find 'py.test')
```

**Comment by ziegenberg** [comment]
If it's okay with you, I would rebase my PR onto the current main. That should solve the _Commit message did not follow Conventional Commits_ error.

**Review by parthea — COMMENTED** [review]
I found that the minimum version of `grpcio` is 1.49.1 for python 3.11. I've updated the setup.py to reflect that.

**Review by parthea — APPROVED** [review]

**Comment by parthea** [comment]
Thanks @ziegenberg!

**Pull request merged**
