### PR TITLE
chore: release 1.31.2

### PR DESCRIPTION
**Pull request by busunkim96**
Manually updating version and Changelog for record keeping purposes.

### CODE REVIEW

**Review by tseaver — APPROVED** [review]

**Comment by tseaver** [comment]
I can't see logs from the failed `OwlBot Post Processor` job. :(

**Comment by busunkim96** [comment]
google-api-core==1.31.2 with the field mask fix is now released @benrkarl

**Comment by busunkim96** [comment]
Hmm I initially had `master` as the base branch and then switched it to `v1`. Maybe that confused the post processor?

**Comment by tseaver** [comment]
I see the release on the cheeseshop: https://pypi.org/project/google-api-core/1.31.2/

**Comment by tseaver** [comment]
@busunkim96 It looks like you were able to merge the PR even without the main [Kokoro build](https://pypi.org/project/google-api-core/1.31.2/) completing:  I believe that PR #241 actually dropped the branch protection for `master`.

**Pull request merged**
